#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
dir=$(mktemp -d -t fly-build-publishers.XXXXX)

tidy () {
    rm -rf "$dir"
}

trap tidy EXIT

mkdir "$dir/version"
echo TEST_VERSION > "$dir/version/tag"

export SENTRY_RELEASE=ignored
export PERCY_BRANCH=local
export PERCY_PROJECT_ID=f10a8acf/boclips-web-app
export PERCY_TOKEN="$(bo show credential concourse-main boclips.boclips-web-app percy-token)"
export NODE_ENV=development

fly --target ci execute \
    --input source="$cwd" \
    --input version="$dir/version" \
    --config "$cwd/pipeline/build.yaml" \
    --output dist=fly-dist
