---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/browsers
    tag: 'node16.13.2-chrome100-ff98'


inputs:
- name: source
- name: version

outputs:
- name: source
- name: dist

caches:
- path: ../../../root/.npm

params:
  PERCY_TOKEN:
  PERCY_PROJECT_ID:
  PERCY_SKIP:

run:
  path: sh
  args:
  - -ec
  - |-
    SENTRY_RELEASE="boclips-web-app-$(cat ../version/tag)"
    export SENTRY_RELEASE
    npm ci
    npm run fake &
    npm run lint
    npm run test
    times=0
    until [ $times -gt 10 ] || curl --fail --silent http://localhost:9000/ > /dev/null
    do
      echo "Waiting for bundle before running tests"
      sleep 1
      times=$(( times + 1 ))
    done
    if [ "${PERCY_SKIP}" = "true" ]
    then
      echo "PERCY_SKIP set to true, skipping percy steps"
      npm run build
    else
      PERCY_TARGET_COMMIT=$(npx percy-baseline-commit)
      echo "$PERCY_TARGET_COMMIT"
      export PERCY_TARGET_COMMIT
      npm run test-visual
      npm run build
      npm run test-visual:wait
    fi
    cp -R ./dist/ ../dist/html/
    cp application.conf Dockerfile ../dist
  dir: source
