---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/browsers
    tag: 'node12.14.1-chrome83-ff77'


inputs:
- name: source
- name: version

outputs:
- name: dist

caches:
- path: ../../../root/.npm

params:
  PERCY_TOKEN:

run:
  path: sh
  args:
  - -ec
  - |-
    SENTRY_RELEASE="boclips-web-app-$(cat ../version/tag)"
    export SENTRY_RELEASE
    npm ci
    npm run test
    npm run lint
    npm run fake &
    npm run test-visual
    npm run build
    cp -R ./dist/ ../dist/html/
    cp application.conf Dockerfile ../dist
  dir: source
