---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/browsers
    tag: 'node12.14.1-chrome83-ff77'


inputs:
- name: source
- name: version
- name: percy-baseline

outputs:
- name: dist

caches:
- path: ../../../root/.npm

params:
  PERCY_TOKEN:

run:
  path: sh
  args:
  - -ec
  - |-
    SENTRY_RELEASE="boclips-web-app-$(cat ../version/tag)"
    export SENTRY_RELEASE
    PERCY_TARGET_COMMIT="$(cat ../percy-baseline/.git/ref)"
    export PERCY_TARGET_COMMIT
    npm ci
    npm run fake &
    npm run test
    npm run lint
    times=0
    until [ $times -gt 10 ] || curl --fail --silent http://localhost:9000/ > /dev/null
    do
      echo "Waiting for bundle before running tests"
      sleep 1
      times=$(( times + 1 ))
    done
    npm run test-visual
    npm run build
    npm run test-visual:wait
    cp -R ./dist/ ../dist/html/
    cp application.conf Dockerfile ../dist
  dir: source
