---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: '12'

inputs:
- name: source
- name: version

outputs:
- name: dist

caches:
- path: ../../../root/.npm

run:
  path: sh
  args:
  - -ec
  - |-
    SENTRY_RELEASE="boclips-web-app-$(cat ../version/tag)"
    export SENTRY_RELEASE
    npm run ci-build
  dir: source
