export type Role = 'ROLE_BOCLIPS_WEB_APP_BROWSE' | 'ROLE_BOCLIPS_WEB_APP_ORDER';

export const ROLES: { [key: string]: Role } = {
  BOCLIPS_WEB_APP_BROWSE: 'ROLE_BOCLIPS_WEB_APP_BROWSE',
  BOCLIPS_WEB_APP_ORDER: 'ROLE_BOCLIPS_WEB_APP_ORDER',
};
